-- This file is now an index for the split schema files in ./schema.
-- Apply them in this order when bootstrapping a new Turso/SQLite database:
--
-- 01_pragmas.sql
-- 10_parties.sql
-- 11_party_type_migration.sql
-- 12_party_planned_time_migration.sql
-- 15_guild_voice_configs.sql
-- 16_guild_schedule_configs.sql
-- 17_guild_schedule_board_state.sql
-- 18_guild_party_channel_configs.sql
-- 19_guild_party_finder_configs.sql
-- 20_party_members.sql
-- 30_party_confirmations.sql
-- 40_schedule_events.sql
-- 42_schedule_event_times.sql
-- 50_schedule_votes.sql
-- 60_party_logs.sql
-- 90_triggers.sql
-- 95_guild_voice_triggers.sql
-- 96_guild_schedule_triggers.sql
-- 97_guild_schedule_board_state_triggers.sql
-- 99_guild_party_channel_triggers.sql
-- 100_guild_party_finder_triggers.sql
-- 98_schedule_event_times_triggers.sql
--
-- Keeping the schema split by concern makes it easier to review and maintain.
